version: 2.1
parameters:
  docker_image:
    type: string
    default: cypress/browsers:node18.12.0-chrome106-ff106
jobs:
  build:
    docker:
      - image: << pipeline.parameters.docker_image >>
    working_directory: ~/repo
    steps:
      - run: apt-get update
      - run: apt-get install -y gnupg dirmngr
      - checkout
      - run: npm ci
      - run:
          name: build
          command: npm run build
          environment:
            WITH_STATS: true
      - run: npm run test:es-check
      - run: npm run print-bundle-size
      - run: npm run test -- --maxWorkers=2
      - run: npm run print-bundle-size
      - save_cache:
          key: spa-dist-{{ .Revision }}
          paths:
            - dist
workflows:
  build_and_test:
    jobs:
      - build
